* grepping <2015-05-11 Mon> 					       :toni:

commands to grep by, for establishing various counts in planning the crop

a good idea to check results prior to wc!

why not turn this into a shell script?  can . . . but commands will vary a
bit from year to year, and it's important to look at the data.  So for now,
I prefer to do this interactively.

#+BEGIN_SRC grep commands 

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred  | wc

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep ",20)." | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep ",10)." | wc


grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | wc

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "\[self\]" | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep selfed 

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep inc | wc

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'S'" | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'S'" | grep pick | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'S'" | grep pick 

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'W'" | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'W'" | grep pick | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'W'" | grep pick 

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'M'" | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'M'" | grep pick | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'M'" | grep pick 

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],1,\[" | grep "'B'" | wc




grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "\[self\]"

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep inc | wc

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'S'" | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'S'" | grep pick | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'S'" | grep pick

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'W'" | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'W'" | grep pick | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'W'" | grep pick 

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'M'" | wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'M'" | grep pick |wc
grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'M'" | grep pick 

grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred | grep "\],2,\[" | grep "'B'" | wc


#+END_SRC


* components of grep strings

Check data uniformity first, e.g., 
   + inbred destinations not embedded in single quotes
   + planting correct for early back-crosses
   + check, not test unless a real genetics experiment


+ grep packing_plan packing_plan.org | grep -v '%' | grep -v inbred |

+ grep ",20)." for row lengths

+ grep "\[self\]" for just selves

+ grep inc for bulks and whatever else is in their plan

+ grep pick

+ grep "'S'" etc.  (imbed in single quotes to not catch maternal ears)

+ grep "\],1,\[" for planting


