% this is 17r/planning/sequenced.packing_plan.pl
% generated by ../maize/crops/merge_plan_data.perl using operation sequence 
% on Tue May 23 05:15:49 CDT 2017 for crop 17r.


packing_plan(1,1,[elite],1,[fly],'','','16R','17R',60,20).
packing_plan(2,1,[elite],1,[fly],'','','16R','17R',60,20).
packing_plan(3,1,[elite],1,[fly],'','','16R','17R',60,20).
packing_plan(4,1,[elite],1,[fly],'','','16R','17R',60,20).
packing_plan(5,1,[elite],1,[fly],'','','16R','17R',60,20).
packing_plan(6,1,[elite],1,[fly],'','','16R','17R',40,20).
packing_plan(7,1,[elite],1,[fly],'','','16R','17R',40,20).
packing_plan(8,1,[elite],1,[fly],'','','16R','17R',40,20).
packing_plan(9,1,[elite],1,[fly],'','','16R','17R',40,20).
packing_plan(10,1,[elite],1,[fly],'','','16R','17R',40,20).
packing_plan(11,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(12,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(13,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(14,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(15,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(16,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(17,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(18,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(19,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(20,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(21,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(22,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(23,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(24,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(25,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(26,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(27,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(28,1,['13R504:B0xxxxxx,13R504:B0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(29,1,['13R504:B0xxxxxx,13R504:B0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(30,1,['13R504:B0xxxxxx,13R504:B0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(31,1,['13R504:B0xxxxxx,13R504:B0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(32,1,['13R504:B0xxxxxx,13R504:B0xxxxxx'],1,[inbred],'','','17R',20,20).
packing_plan(33,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(34,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(35,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(36,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(37,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(38,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(39,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(40,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(41,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(42,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(43,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(44,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(45,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(46,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(47,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(48,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(49,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(50,1,['13R504:B0xxxxxx,13R504:B0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(51,1,['13R504:B0xxxxxx,13R504:B0xxxxxx'],2,[inbred],'','','17R',20,20).
packing_plan(52,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],3,[inbred],'','','17R',20,20).
packing_plan(53,1,['09R201:S0xxxxxx,09R201:S0xxxxxx'],3,[inbred],'','','17R',20,20).
packing_plan(54,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],3,[inbred],'','','17R',20,20).
packing_plan(55,1,['09R301:W0xxxxxx,09R301:W0xxxxxx'],3,[inbred],'','','17R',20,20).
packing_plan(56,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],3,[inbred],'','','17R',20,20).
packing_plan(57,1,['09R401:M0xxxxxx,09R401:M0xxxxxx'],3,[inbred],'','','17R',20,20).
packing_plan(58,1,['16R405:M0003112','16R4222:0009405'],1,[inc,self,'B',fly],'is 6th!','K0202','17R',20,20).
packing_plan(59,1,['16R405:M0003112','16R4222:0009405'],2,[inc,self,'B',fly],'is 6th!','K0202','17R',20,20).
packing_plan(60,1,['16R405:M0001811','16R4356:0010005'],1,[inc,self,'B',fly],'is 6th!; phe 17.7 in 16r','K2212','17R',20,20).
packing_plan(61,1,['16R405:M0001811','16R4356:0010005'],2,[inc,self,'B',fly],'is 6th!; phe 17.7 in 16r','K2212','17R',20,20).
packing_plan(62,1,['13R205:S0002205','13R4082:0005502'],1,[inc,self,fly],'is 6th!; additional bulking good','K0302','17R',20,20).
packing_plan(63,1,['13R205:S0002205','13R4082:0005502'],2,[inc,self,fly],'is 6th!; additional bulking good','K0302','17R',20,20).
packing_plan(64,1,['13R305:W0000702','13R4083:0005603'],1,[inc,self,fly],'is 6th!; no phe 17.7 16r, but appeared later; check osc; forbear male had great phenotype, smaller lesions on lower leaves than Mo20W on 9.1 in 12n; sheath lesions were more diagnostic','K0302','17R',20,20).
packing_plan(65,1,['13R305:W0000702','13R4083:0005603'],2,[inc,self,fly],'is 6th!; no phe 17.7 16r, but appeared later; check osc; forbear male had great phenotype, smaller lesions on lower leaves than Mo20W on 9.1 in 12n; sheath lesions were more diagnostic','K0302','17R',20,20).
packing_plan(66,1,['14R205:S0000215','14R4229:0009701'],1,[inc,self,'B',fly],'is 6th!','K0303','17R',20,20).
packing_plan(67,1,['14R205:S0000215','14R4229:0009701'],2,[inc,self,'B',fly],'is 6th!','K0303','17R',20,20).
packing_plan(68,1,['12R405:M0000310','12R3587:0023110'],1,[inc,self,fly],'is 6th!; phenotype 9.1 in 12n; phe 17.7 in 16r','K0303','17R',20,20).
packing_plan(69,1,['12R405:M0000310','12R3587:0023110'],2,[inc,self,fly],'is 6th!; phenotype 9.1 in 12n; phe 17.7 in 16r','K0303','17R',20,20).
packing_plan(70,1,['12N205:S0036705','12N3948:0017506'],1,[inc,self,'B',fly],'is 6th!; check osc; male had good phenotype 9.1 in 12n; phe 17.7 in 16r','K2101','17R',20,20).
packing_plan(71,1,['12N205:S0036705','12N3948:0017506'],2,[inc,self,'B',fly],'is 6th!; check osc; male had good phenotype 9.1 in 12n; phe 17.7 in 16r','K2101','17R',20,20).
packing_plan(72,1,['12N305:W0038310','12N3949:0017706'],1,[inc,self,fly],'is 6th!; in 12n, male had weak phenotype 9.1, better by 13.1, but good phenotype by 15.1; no phe 17.7 in 16r','K2101','17R',20,20).
packing_plan(73,1,['12N305:W0038310','12N3949:0017706'],2,[inc,self,fly],'is 6th!; in 12n, male had weak phenotype 9.1, better by 13.1, but good phenotype by 15.1; no phe 17.7 in 16r','K2101','17R',20,20).
packing_plan(74,1,['11N405:M0032808','11N3419:0010704'],1,[self,inc,fly],'is 6th!; addtnl bulking good; check osc; male had good phenotype 9.1 in 12n; phe 17.7 in 16r','K2101','17R',20,20).
packing_plan(75,1,['11N405:M0032808','11N3419:0010704'],2,[self,inc,fly],'is 6th!; addtnl bulking good; check osc; male had good phenotype 9.1 in 12n; phe 17.7 in 16r','K2101','17R',20,20).
packing_plan(76,1,['15R305:W0000711','15R4352:0010904'],1,[inc,self,'B',fly],'is 6th; no phe 17.7 in 16r; repeat of 16r','K2106','17R',20,20).
packing_plan(77,1,['14R305:W0000803','14R3958:0010412'],2,[inc,self,'B',fly],'is 6th; no phe 17.7 in 16r; repeat of 16r','K2106','17R',20,20).
packing_plan(78,1,['15R405:M0001101','15R4353:0011002'],1,[inc,self,'B',fly],'is 6th; phe 17.7 in 16r','K2106','17R',20,20).
packing_plan(79,1,['15R405:M0001101','15R4353:0011002'],2,[inc,self,'B',fly],'is 6th; phe 17.7 in 16r','K2106','17R',20,20).
packing_plan(80,1,['16R305:W0001610','16R4279:0010511'],1,[inc,self,'B',fly],'is 6th!; fungus; no phe 15r; phe 17.7 in 16r; crummy tassels in 14r','K2312','17R',20,20).
packing_plan(81,1,['16R305:W0001610','16R4279:0010511'],2,[inc,self,'B',fly],'is 6th!; fungus; no phe 15r; phe 17.7 in 16r; crummy tassels in 14r','K2312','17R',20,20).
packing_plan(82,1,['16R205:S0001202','16R4390:0010609'],1,[inc,self,'B',fly],'is 6th!; no phe 15r; phe 17.7 in 16r','K2312','17R',20,20).
packing_plan(83,1,['16R205:S0001202','16R4390:0010609'],2,[inc,self,'B',fly],'is 6th!; no phe 15r; phe 17.7 in 16r','K2312','17R',20,20).
packing_plan(84,1,['14R405:M0001105','14R4283:0021405'],1,[inc,self,'B',fly],'is 6th!; may be fast; phe 17.7 in 16r','K0604','17R',20,20).
packing_plan(85,1,['14R405:M0001105','14R4283:0021405'],2,[inc,self,'B',fly],'is 6th!; may be fast; phe 17.7 in 16r','K0604','17R',20,20).
packing_plan(86,1,['14R205:S0000105','14R4284:0021512'],1,[inc,self,'B',fly],'is 6th!','K2405','17R',20,20).
packing_plan(87,1,['14R205:S0000105','14R4284:0021512'],2,[inc,self,'B',fly],'is 6th!','K2405','17R',20,20).
packing_plan(88,1,['12N305:W0039207','12N3614:0024110'],1,[inc,self,fly],'is 6th!; poor yield on 13r selves','K2405','17R',20,20).
packing_plan(89,1,['12N305:W0039207','12N3614:0024110'],2,[inc,self,fly],'is 6th!; poor yield on 13r selves','K2405','17R',20,20).
packing_plan(90,1,['14R405:M0001103','14R4285:0021603'],1,[inc,self,'B',fly],'is 6th!','K2405','17R',20,20).
packing_plan(91,1,['14R405:M0001103','14R4285:0021603'],2,[inc,self,'B',fly],'is 6th!','K2405','17R',20,20).
packing_plan(92,1,['16R205:S0001210','16R4391:0010710'],1,[inc,self,'B',fly],'is 6th!; phe 17.7 in 16r','K2506','17R',20,20).
packing_plan(93,1,['16R205:S0001210','16R4391:0010710'],2,[inc,self,'B',fly],'is 6th!; phe 17.7 in 16r','K2506','17R',20,20).
packing_plan(94,1,['16R405:M0003214','16R4510:0011204'],1,[inc,self,'B',fly],'is 6th!; male had phe 17.7 in 16r; pick one of three','K0901','17R',20,20).
packing_plan(95,1,['16R405:M0003214','16R4510:0011204'],2,[inc,self,'B',fly],'is 6th!; male had phe 17.7 in 16r; pick one of three','K0901','17R',20,20).
packing_plan(96,1,['16R405:M0003206','16R4511:0011304'],1,[inc,self,'B',fly],'is 6th!; male had phe 17.7 in 16r; alternate for 16R405:M0003214; pick one of three','K0901','17R',20,20).
packing_plan(97,1,['16R405:M0003206','16R4511:0011304'],2,[inc,self,'B',fly],'is 6th!; male had phe 17.7 in 16r; alternate for 16R405:M0003214; pick one of three','K0901','17R',20,20).
packing_plan(98,1,['16R405:M0003312','16R4027:0012203'],1,[inc,self,'B',fly],'is 6th!; alternate for 12R405:M0011105; 3/5 mutants, also segregating for semi-dwarfism','K3007','17R',20,20).
packing_plan(99,1,['16R405:M0003312','16R4027:0012203'],2,[inc,self,'B',fly],'is 6th!; alternate for 12R405:M0011105; 3/5 mutants, also segregating for semi-dwarfism','K3007','17R',20,20).
packing_plan(100,1,['16R405:M0000808','16R4298:0012403'],1,[inc,self,'B',fly],'is 6th!; phe 17.7 in 16r; preferred in 16r; alternate for 12R405:M0011105','K3007','17R',20,20).
packing_plan(101,1,['16R405:M0000808','16R4298:0012403'],2,[inc,self,'B',fly],'is 6th!; phe 17.7 in 16r; preferred in 16r; alternate for 12R405:M0011105','K3007','17R',20,20).
packing_plan(102,1,['16R405:M0002208','16R4300:0012606'],1,[inc,self,'B',fly],'is 6th!; male had phe 17.7 in 16r; tendency to crummy tassel','K1411','17R',20,20).
packing_plan(103,1,['16R405:M0002208','16R4300:0012606'],2,[inc,self,'B',fly],'is 6th!; male had phe 17.7 in 16r; tendency to crummy tassel','K1411','17R',20,20).
packing_plan(104,1,['15R205:S0000101,15R4183:0017105'],1,[inc,self,'B',fly],'is 6th!; no phe 17.7 in 16r but appeared later in 2/8 plants','K7205','17R',20,20).
packing_plan(105,1,['15R205:S0000101,15R4183:0017105'],2,[inc,self,'B',fly],'is 6th!; no phe 17.7 in 16r but appeared later in 2/8 plants','K7205','17R',20,20).
packing_plan(106,1,['15R305:W0000701,15R4363:0017408'],1,[inc,self,'B',fly],'is 6th!; phe 17.7 in 16r; preferred','K7205','17R',20,20).
packing_plan(107,1,['15R305:W0000701,15R4363:0017408'],2,[inc,self,'B',fly],'is 6th!; phe 17.7 in 16r; preferred','K7205','17R',20,20).
packing_plan(108,1,['16R205:S0001303','16R4537:0014611'],1,[inc,self,'B',fly],'is 6th!; male had phe 17.7 in 16r','K12205','17R',20,20).
packing_plan(109,1,['16R205:S0001303','16R4537:0014611'],2,[inc,self,'B',fly],'is 6th!; male had phe 17.7 in 16r','K12205','17R',20,20).
packing_plan(110,1,['09R201:S0056209','09R1416:0025907'],1,['S'],'is 1st; forebear','K6711','17R',40,20).
packing_plan(111,1,['09R201:S0040305','09R1416:0025907'],1,['S'],'is 1st; sib of 09R201:S0056209','K6711','17R',40,20).
packing_plan(112,1,['10R205:S0002302','10R2252:0031702'],1,['S'],'is 2nd; forbear of 12R205:S0008815 and 12R205:S0009109','K6711','17R',40,20).
packing_plan(113,1,['12R205:S0008815','12R3270:0014314'],1,['S'],'is 3rd','K6711','17R',40,20).
packing_plan(114,1,['12R205:S0009109','12R3270:0014314'],1,['S'],'is 3rd','K6711','17R',40,20).
packing_plan(115,1,['14R305:W0000703','14R4137:0004215'],1,['W'],'is 5th','K6711','17R',40,20).
packing_plan(116,1,['14R305:W0000716','14R4137:0004215'],1,['W'],'is 5th','K6711','17R',40,20).
packing_plan(117,1,['14R305:W0000705','14R4137:0004215'],1,['W'],'is 5th','K6711','17R',40,20).
packing_plan(118,1,['09R401:M0040909','09R1416:0025906'],1,['M'],'is 1st; forebear','K6711','17R',40,20).
packing_plan(119,1,['10R405:M0000715','10R2254:0032002'],1,['M'],'is 2nd; forebear of 12R405:M0009302 and 12R405:M0011707','K6711','17R',40,20).
packing_plan(120,1,['10R405:M0001010','10R2254:0032002'],1,['M'],'is 2nd; sib of 10R405:M0000715','K6711','17R',40,20).
packing_plan(121,1,['10R405:M0006607','10R2254:0032003'],1,['M'],'is 2nd; sib of 10R405:M0000715','K6711','17R',40,20).
packing_plan(122,1,['10R405:M0006610','10R2254:0032010'],1,['M'],'is 2nd; sib of 10R405:M0000715','K6711','17R',40,20).
packing_plan(123,1,['12R405:M0009302','12R3486:0014708'],1,['M'],'is 3rd; has repeatedly failed','K6711','17R',40,20).
packing_plan(124,1,['12R405:M0011707','12R3486:0014708'],1,['M'],'is 3rd; sib of 12R405:M0009302','K6711','17R',40,20).
packing_plan(125,1,['16R305:W0001401','16R4467:0004309'],1,[self],'is 6th!; male had phe 17.7 16r','K1802','17R',15,10).
packing_plan(126,1,['16R405:M0001705','16R4468:0004411'],1,[self],'is 5th; male had phe 17.7 16r','K1802','17R',15,10).
packing_plan(127,1,['16R305:W0001408','16R4470:0004603'],1,[self],'is 5th; male had phe 17.7 16r','K1804','17R',15,10).
packing_plan(128,1,['16R405:M0001707','16R4471:0004707'],1,[self],'is 4th; male had phe 17.7 16r','K1804','17R',15,10).
packing_plan(129,1,['16R205:S0001309','16R4472:0004811'],1,[self],'is 4th; male had phe 17.7 16r','K3514','17R',15,10).
packing_plan(130,1,['16R305:W0001511','16R4473:0004903'],1,[self],'is 5th; male had phe 17.7 16r','K3514','17R',15,10).
packing_plan(131,1,['16R405:M0003103','16R4474:0005001'],1,[self],'is 4th; male had phe 17.7 16r','K3514','17R',20,10).
packing_plan(132,1,['16R305:W0000714','16R4475:0005105'],1,[self],'is 4th; male had phe 17.7 16r','K16306','17R',15,10).
packing_plan(133,1,['16R405:M0003107','16R4476:0005202'],1,[self],'is 4th; male had phe 17.7 16r','K16306','17R',15,10).
packing_plan(134,1,['16R305:W0001612','16R4477:0005303'],1,[self],'is 1st in W; dominant mutant in row? contaminant?; phe 17.7 16r','K16306','17R',15,10).
packing_plan(135,1,['16R305:W0001618','16R4477:0005311'],1,[self],'is 1st in W; dominant mutant in row? contaminant?; phe 17.7 16r','K16306','17R',15,10).
packing_plan(136,1,['16R405:M0001704','16R4477:0005305'],1,[self],'is 1st in M; dominant mutant in row? contaminant?; phe 17.7 16r','K16306','17R',15,10).
packing_plan(137,1,['16R405:M0001708','16R4477:0005303'],1,[self],'is 1st in M; dominant mutant in row? contaminant?; phe 17.7 16r','K16306','17R',15,10).
packing_plan(138,1,['16R205:S0001112','16R4478:0005404'],1,[self],'is 3rd; male had phe 17.7 16r; sometimes late developping phenotype; yellow-green splotchies, earlier in the process of lesion formation; very different from K11903; favored lower leaves in 12r; cross all plants blindly; may be functionally recessive; excellent light-brown necrotic lesion phenotype 8.1 in 12n, well before flowering; evidence of small, slight oscillations','K11906','17R',15,10).
packing_plan(139,1,['16R305:W0000702','16R4481:0005706'],1,[self],'is 3rd; male had phe 17.7 16r and preferred then; sometimes late developping phenotype; yellow-green splotchies, earlier in the process of lesion formation; very different from K11903; favored lower leaves in 12r; cross all plants blindly; may be functionally recessive; excellent light-brown necrotic lesion phenotype 8.1 in 12n, well before flowering; evidence of small, slight oscillations','K11906','17R',15,10).
packing_plan(140,1,['16R405:M0002211','16R4482:0005809'],1,[self],'is 3rd; male had phe 17.7 16r and preferred then; sometimes late developping phenotype; yellow-green splotchies, earlier in the process of lesion formation; very different from K11903; favored lower leaves in 12r; cross all plants blindly; may be functionally recessive; excellent light-brown necrotic lesion phenotype 8.1 in 12n, well before flowering; evidence of small, slight oscillations','K11906','17R',15,10).
packing_plan(141,1,['16R4460:0003602','16R4460:0003602'],1,[check,'S'],'is 3rd selfed','K1702','17R',15,10).
packing_plan(142,1,['16R4460:0003602','16R4460:0003602'],1,[check,'S'],'is 3rd selfed','K1702','17R',15,10).
packing_plan(143,1,['16R4461:0003713','16R4461:0003713'],1,[check,'W'],'is 3rd selfed','K3402','17R',15,10).
packing_plan(144,1,['16R4461:0003713','16R4461:0003713'],1,[check,'W'],'is 3rd selfed','K3402','17R',15,10).
packing_plan(145,1,['16R4462:0003808','16R4462:0003808'],2,[check,'M'],'is 2nd selfed','K3402','17R',15,10).
packing_plan(146,1,['16R4462:0003808','16R4462:0003808'],2,[check,'M'],'is 2nd selfed','K3402','17R',15,10).
packing_plan(147,1,['16R4463:0003902','16R4463:0003902'],1,[check,'W'],'is 3rd selfed','K5302','17R',15,10).
packing_plan(148,1,['16R4463:0003902','16R4463:0003902'],1,[check,'W'],'is 3rd selfed','K5302','17R',15,10).
packing_plan(149,1,['16R4464:0004010','16R4464:0004010'],1,[check,'M'],'is 3rd selfed','K5302','17R',15,10).
packing_plan(150,1,['16R4464:0004010','16R4464:0004010'],1,[check,'M'],'is 3rd selfed','K5302','17R',15,10).
packing_plan(151,1,['16R4484:0006001','16R4484:0006001'],2,[check,'S'],'is 1st selfed in S; recessive','K68503','17R',15,10).
packing_plan(152,1,['16R4485:0006103','16R4485:0006103'],2,[check,'W'],'is 1st selfed in W; recessive','K68503','17R',15,10).
packing_plan(153,1,['16R4486:0006204','16R4486:0006204'],2,[check,'M'],'is 1st selfed in M; recessive','K68503','17R',15,10).
packing_plan(154,1,['16R4487:0006309','16R4487:0006309'],2,[check,'S'],'is 1st selfed in S; recessive','K68507','17R',15,10).
packing_plan(155,1,['16R4488:0006409','16R4488:0006409'],2,[check,'W'],'is 1st selfed in W; recessive','K68507','17R',15,10).
packing_plan(156,1,['16R4489:0006503','16R4489:0006503'],2,[check,'M'],'is 1st selfed in M; recessive','K68507','17R',15,10).
packing_plan(157,1,['16R4465:0004111','16R4465:0004111'],1,[check,'S'],'is 3rd selfed','K1802','17R',15,10).
packing_plan(158,1,['16R4466:0004206','16R4466:0004206'],1,[check,'S'],'is 3rd selfed; check sex organs; 15r had excellent tassel and no ear','K16306','17R',15,10).
packing_plan(159,1,['15R4370:0006703','15R4370:0006703'],1,[check,'S'],'is 3rd selfed; no phe 17.7 16r; repeat of 16r','K1804','17R',15,10).
packing_plan(160,1,['14R205:S0002812','14R4236:0017206'],1,[check,'S'],'is 3rd selfed; no phe 17.7 16r; repeat of 16r','K1804','17R',15,10).
packing_plan(161,1,['15R4372:0007201','15R4372:0007201'],1,[check,'M'],'is 3rd selfed; phe 17.7 16r; repeat of 16r for insurance','K3514','17R',15,10).
packing_plan(162,1,['15R305:W0000908','15R4373:0007409'],2,[check,'S','W','M'],'dominant mutant in row? contaminant?; phe 17.7 16r; repeat of 16r','K16306','17R',15,10).
packing_plan(163,1,['16R405:M0002212','16R4496:0009201'],1,['M'],'is 3rd; branch rebuild; phe 17.7 in 16r','K0106','17R',15,10).
packing_plan(164,1,['14R305:W0000704','14R4220:0006819'],1,['W'],'is 4th; repeat of 15r and 16r; phe 17.7 in 16r','K0202','17R',15,10).
packing_plan(165,1,['16R305:W0001406','16R4498:0009505'],1,['W'],'is 3rd; branch rebuild; male had phe 17.7 in 16r','K0207','17R',15,10).
packing_plan(166,1,['16R305:W0002911','16R4499:0009614'],1,['W'],'is 3rd; branch rebuild; later phe in 15r; male had phe 17.7 in 16r','K0207','17R',15,10).
packing_plan(167,1,['13R405:M0002605','13R4148:0019101'],1,['M'],'is 5th; repeat 15r and 16r; 13R405:M0002601 had only 3 plants in 16r and no phe 17.7','K5515','17R',30,10).
packing_plan(168,1,['16R205:S0002616','16R4445:0009807'],1,['S'],'is 5th; male had phe 17.7 in 16r','K5525','17R',15,10).
packing_plan(169,1,['16R305:W0001411','16R4393:0009910'],1,['W'],'is 3rd; may be chlorotic; one mutant in 15r; phe 17.7 in 16r','K5525','17R',15,10).
packing_plan(170,1,['10R305:W0001502','10R1035:0021906'],1,['W'],'is 3rd; no phe 15r; repeat 16r; no phe 17.7 in 16r but several mutants appeared later; ancestor of 13R305:W0000803; stalled branch?; pick one of two','K0509','17R',15,10).
packing_plan(171,1,['10R305:W0001511','10R1035:0021903'],1,['W'],'is 3rd; no phe 15r; repeat 16r; no phe 17.7 in 16r but appeared later; alternate for 11N305:W0039501; stalled branch?; pick one of two','K0509','17R',15,10).
packing_plan(172,1,['11N305:W0039501','11N3192:0013810'],1,['W'],'is 4th; no phe 15r;  repeat 16r; no phe 17.7 in 16r but appeared later; forebear of 13R305:W000080; stalled branch?; pick one of two','K0509','17R',15,10).
packing_plan(173,1,['16R305:W0001607','16R3607:0010403'],1,['W'],'is 5th; no phe 15r; no phe 17.7 in 16r but appeared later; alternate for 11N305:W0039501; stalled branch?; pick one of two','K0509','17R',15,10).
packing_plan(174,1,['16R405:M0002210','16R4392:0010801'],1,['M'],'is 5th; phe 17.7 in 16r; forebears had poor germination in 15r and 16r; overplant','K2506','17R',30,10).
packing_plan(175,1,['16R205:S0002711','16R4507:0010903'],1,['S'],'is 5th; phe 17.7 in 16r; fast; forebear had no ears in 12r; male parent had bad tassel in 14r','K2606','17R',15,10).
packing_plan(176,1,['16R405:M0003314','16R4508:0011011'],1,['M'],'is 3rd; phe 17.7 in 16r; may be fast; alternate branch for 15R405:M0003909','K2606','17R',15,10).
packing_plan(177,1,['15R405:M0003909','15R4398:0013904'],1,['M'],'is 3rd; phe 17.7 in 16r; repeat 16r; may be fast; tassel looked sterile in 15r, but this is the progeny','K2606','17R',15,10).
packing_plan(178,1,['16R205:S0000613','16R4513:0011501'],1,['S'],'is 4th; clear phe 15r; phe 17.7 in 16r; alternate branch for 12R205:S0002216; given metabolic effects, cut out most wild-types','K1001','17R',20,10).
packing_plan(179,1,['16R205:S0000602','16R4007:0011605'],1,['S'],'is 5th; finally got this far; clear phe 15r; phe 17.7 in 16r; a few ok tassels in 14r; check osc; missed in 12n; phenotype poor; given metabolic effects, cut out most wild-types','K1001','17R',20,10).
packing_plan(180,1,['12R205:S0002217','12R3454:0028708'],1,['S'],'is 3rd; repeat of 13r, 14r, 15r; phe 17.7 in 16r; good ears and tassels on some plants in 14r; modifier jump in 12n; given metabolic effects, cut out most wild-types','K2711','17R',20,10).
packing_plan(181,1,['16R205:S0000604','16R4011:0011703'],1,['S'],'is 4th; check phenotype against 12R205:S0002217 carefully; phe 17.7 in 16r; good ears and tassels on some plants in 14r; modifier jump in 12n; given metabolic effects, cut out most wild-types','K2711','17R',20,10).
packing_plan(182,1,['16R305:W0001502','16R4514:0011806'],1,['W','M'],'is 4th','K1109','17R',15,10).
packing_plan(183,1,['16R405:M0002103','16R4516:0012007'],1,['M'],'is 3rd; male had phe 17.7 in 16r','K2805','17R',15,10).
packing_plan(184,1,['15R405:M0001310','15R4401:0014902'],1,['M'],'is 5th; repeat 16r; phe 17.7 in 16r; overplant','K3206','17R',30,10).
packing_plan(185,1,['15R205:S0002306','15R4403:0015507'],1,['S'],'is 3rd; repeat 16r; overplant; no phe 17.7 in 16r; only 2 plants','K7110','17R',30,10).
packing_plan(186,1,['16R305:W0003012','16R4526:0013504'],1,['W'],'is 3rd; male had phe 17.7 in 16r','K7110','17R',30,10).
packing_plan(187,1,['16R305:W0003016','16R4528:0013704'],1,['W'],'is 4th; male had phe 17.7 in 16r; preferred in 16r','K7110','17R',30,10).
packing_plan(188,1,['15R305:W0002904','15R3654:0016401'],1,['W'],'is 5th; repeat 16r; overplant; no phe 17.7 in 16r, 0/12 plants','K7110','17R',30,10).
packing_plan(189,1,['16R405:M0003204','16R4531:0014008'],1,['M'],'is 4th; no phe 17.7 in 16r but appeared later in 4/8 plants','K7110','17R',30,10).
packing_plan(190,1,['16R405:M0002004','16R4532:0014101'],1,['M'],'is 5th; no phe 17.7 in 16r but appeared later in 5/6 plants','K7110','17R',30,10).
packing_plan(191,1,['16R205:S0002715','16R4519:0012802'],2,['S','M'],'is 2nd; recreated from martys; alternate; phe 17.7 in 16r','K68602','17R',30,10).
packing_plan(192,1,['16R305:W0003006','16R4520:0012908'],2,['W','M'],'is 2nd; recreated from martys; alternate; phe 17.7 in 16r','K68602','17R',30,10).
packing_plan(193,1,['15R0686:0000000','15R0686:0000000'],2,['M'],'is 1st; forebear of 15R405:M0003411, which had no phe 17.7 16r','K68602','17R',30,10).
packing_plan(194,1,['15R205:S0002411','15R0686:0015307'],2,['S'],'is 1st; repeat 16r; recreated from martys; phe 17.7 in 16r','K68607','17R',30,10).
packing_plan(195,1,['16R305:W0001416','16R4523:0013207'],2,['W'],'is 2nd; recreated from martys; phe 17.7 in 16r','K68607','17R',30,10).
packing_plan(196,1,['15R405:M0001601','15R0686:0015307'],2,['M'],'is 1st; repeat 16r; recreated from martys; phe 17.7 in 16r','K68607','17R',30,10).
packing_plan(197,1,['14R405:M0001610','14R4048:0026106'],1,['M'],'is 4th; repeat 15r and 16r; phe 17.7 in 16r; overplant; check osc; stems may be brittle','K3311','17R',30,10).
packing_plan(198,1,['15R205:S0002104','15R0667:0021107'],2,['S','W'],'is 1st','K66707','17R',15,10).
packing_plan(199,1,['15R405:M0003601','15R0667:0021107'],2,['W','M'],'is 1st','K66707','17R',15,10).
packing_plan(200,1,['15R205:S0002310','15R0668:0021201'],2,['S','W'],'is 1st','K66801','17R',15,10).
packing_plan(201,1,['15R405:M0003501','15R0668:0021201'],2,['W','M'],'is 1st','K66801','17R',15,10).
packing_plan(202,1,['15R205:S0002601','15R0669:0021307'],2,['S'],'is 1st','K66907','17R',15,10).
packing_plan(203,1,['15R305:W0002804','15R0669:0021307'],2,['W'],'is 1st','K66907','17R',15,10).
packing_plan(204,1,['15R405:M0003407','15R0669:0021307'],2,['M'],'is 1st','K66907','17R',15,10).
packing_plan(205,1,['15R205:S0002511','15R0669:0021311'],2,['S','W','M'],'is 1st','K66911','17R',15,10).
packing_plan(206,1,['15R205:S0002403','15R0670:0021405'],2,['S'],'is 1st','K67005','17R',15,10).
packing_plan(207,1,['15R305:W0002905','15R0670:0021405'],2,['W'],'is 1st','K67005','17R',15,10).
packing_plan(208,1,['15R405:M0003408','15R0670:0021405'],2,['M'],'is 1st','K67005','17R',15,10).
packing_plan(209,1,['15R205:S0002404','15R0671:0021502'],2,['S','W'],'is 1st','K67102','17R',15,10).
packing_plan(210,1,['15R405:M0003403','15R0671:0021502'],2,['W','M'],'is 1st','K67102','17R',15,10).
packing_plan(211,1,['15R205:S0002408','15R0672:0021608'],2,['S','W'],'is 1st','K67208','17R',15,10).
packing_plan(212,1,['15R405:M0003504','15R0672:0021608'],2,['W','M'],'is 1st','K67208','17R',15,10).
packing_plan(213,1,['15R205:S0002206','15R0673:0021705'],2,['S','W'],'is 1st','K67305','17R',15,10).
packing_plan(214,1,['15R405:M0003618','15R0673:0021705'],2,['W','M'],'is 1st','K67305','17R',15,10).
packing_plan(215,1,['15R405:M0003717','15R0674:0021810'],2,['S','W','M'],'is 1st','K67410','17R',15,10).
packing_plan(216,1,['15R405:M0003502','15R0675:0021910'],2,['S','W','M'],'is 1st','K67510','17R',15,10).
packing_plan(217,1,['15R205:S0002309','15R0676:0022002'],2,['S','W'],'is 1st','K67602','17R',15,10).
packing_plan(218,1,['15R405:M0003303','15R0676:0022002'],2,['W','M'],'is 1st','K67602','17R',15,10).
packing_plan(219,1,['15R205:S0002401','15R0677:0022110'],2,['S','W'],'is 1st','K67710','17R',15,10).
packing_plan(220,1,['15R405:M0003611','15R0677:0022110'],2,['W','M'],'is 1st','K67710','17R',15,10).
packing_plan(221,1,['15R405:M0003711','15R0678:0022212'],2,['S','W','M'],'is 1st','K67812','17R',15,10).
packing_plan(222,1,['15R205:S0002208','15R0679:0022304'],2,['S','W'],'is 1st','K67904','17R',15,10).
packing_plan(223,1,['15R405:M0003807','15R0679:0022304'],2,['W','M'],'is 1st','K67904','17R',15,10).
packing_plan(224,1,['15R205:S0002410','15R0680:0022411'],2,['S','W'],'is 1st','K68011','17R',15,10).
packing_plan(225,1,['15R405:M0003613','15R0680:0022411'],2,['W','M'],'is 1st','K68011','17R',15,10).
packing_plan(226,1,['15R405:M0001213','15R0681:0022505'],2,['S','W','M'],'is 1st','K68105','17R',15,10).
packing_plan(227,1,['15R405:M0001305','15R0682:0022603'],2,['S','W','M'],'is 1st','K68203','17R',15,10).
packing_plan(228,1,['15R405:M0001618','15R0683:0022701'],2,['S','W','M'],'is 1st','K68301','17R',15,10).
packing_plan(229,1,['15R405:M0001904','15R0684:0022802'],2,['S','W','M'],'is 1st','K68402','17R',15,10).
packing_plan(230,1,['16R205:S0002604','16R0687:0014708'],2,[check,'S','W','M'],'is 1st; may need to self; Gardner landrace doubled haploid; lesions','K68708','17R',15,10).
packing_plan(231,1,['16R0688:0014805','16R0688:0014805'],2,['S','W','M'],'Gardner landrace doubled haploid; lesions','K68805','17R',15,10).
packing_plan(232,1,['16R0689:0014903','16R0689:0014903'],2,['S','W','M'],'Gardner landrace doubled haploid; lesions','K68903','17R',15,10).
packing_plan(233,1,['16R0690:0000000','16R0690:0000000'],2,['S','W','M'],'repeat 16r; Gardner landrace doubled haploid; lesions','K69000','17R',15,10).
packing_plan(234,1,['16R205:S0000603','16R0691:0015106'],2,[check,'S','M'],'is 1st; may need to self; Gardner landrace doubled haploid; lesions','K69106','17R',15,10).
packing_plan(235,1,['16R305:W0000711','16R0691:0015106'],2,[check,'W','M'],'is 1st; may need to self; Gardner landrace doubled haploid; lesions','K69106','17R',15,10).
packing_plan(236,1,['16R205:S0002607','16R0693:0015303'],2,[check,'S','W','M'],'is 1st may need to self;; Gardner landrace doubled haploid; lesions','K69300','17R',15,10).
packing_plan(237,1,['16R0694:0000000','16R0694:0000000'],2,['S','W','M'],'repeat 16r; Gardner landrace doubled haploid; lesions','K69400','17R',15,10).
packing_plan(238,1,['16R205:S0001111','16R0698:0015802'],2,[check,'S','W','M'],'is 1st; may need to self; Gardner landrace doubled haploid; lesions','K69800','17R',15,10).
packing_plan(239,1,['16R0700:0000000','16R0700:0000000'],2,['S','W','M'],'repeat 16r; Gardner landrace doubled haploid; lesions','K70000','17R',15,10).
packing_plan(240,1,['16R0701:0000000','16R0701:0000000'],2,['S','W','M'],'repeat 16r; Gardner landrace doubled haploid; lesions; poor germination; repeat','K70100','17R',15,10).
